### ISSUE TITLE
Buggy AXIS firmware does not comply with the RTCP protocol

### ISSUE THREAD

**Issue by DongzhongZheng** [elsampsa/valkka-core#14]
Hello!
When I run lesson_2_a, the result is as follow.
![image](https://user-images.githubusercontent.com/44435640/72067628-2b7eff00-331e-11ea-9747-6489413eb815.png)
How to deal with this promblem?
Thank you!

**Comment by elsampsa** [comment]
Its just a message informing an extra communication with the RTSP camera

No need to worry about it

Do you have any other "problems" apart from the message?

**Comment by DongzhongZheng** [comment]
Yes, as shown in the picture above, I can not get any frame. My camera is HIKVISION. Is this lesson can only run on AXIS camera?

**Comment by elsampsa** [comment]
> Is this lesson can only run on AXIS camera?

It works with all (rtsp) cameras, including hikvision.

Are you able to connect to your camera with some other program, say, vlc:
```
vlc -vvv rtsp://username:password@ip
```

I suppose you have edited ```lesson_2_a.py``` to use your correct username, passwd and ip address..?

**Comment by DongzhongZheng** [comment]
OK. Thank you.

**Comment by DongzhongZheng** [comment]
when I am in Extranet, I can use  vlc -vvv rtsp://username:password@ip to get connection with my camera, but I can not connect the camera if I run test_studio_1.py. Why ?

**Comment by DongzhongZheng** [comment]
I can run test_studio_1.py successfully when I am in intranet

**Comment by DongzhongZheng** [comment]
How can I connect to my camera when I am in extranet ?

**Comment by elsampsa** [comment]
You also asked in a private message, how to connect to an ip camera over internet.

When streaming over internet, most of the ports might be closed or udp traffic blocked.

So, you should try tcp (instead of udp) transport for live streaming.  It'll transport the stream through port 554 using tcp protocol for the video stream also (instead of some random udp ports).

Modify example 2 of the tutorial like this:
```
ctx =LiveConnectionContext(LiveConnectionType_rtsp, "rtsp://admin:nordic12345@192.168.1.41", 1, av_in_filter)
ctx.request_tcp = True
```
Reference for that is [here](https://elsampsa.github.io/valkka-core/html/structLiveConnectionContext.html#a99bd3873a382831ff61c51d66a128b0a)

**Comment by DongzhongZheng** [comment]
I got it. Thank you.
