### ISSUE TITLE
Dependency Issue When Installing Valkka to Nvidia Jetson Nano

### ISSUE THREAD

**Issue by canozcivelek** [elsampsa/valkka-core#15]
Hi,

I've been meaning to use Valkka on my Nvidia Jetson Nano, however, as I was following the instructions on how to install the library, I ran into a dependency issue where when I run the "apt-get install valkka", an error is given that the "libstdc++5" dependency is missing.

I've also tried installing it with the "Hacky mode" and after cloning the repo, when I run "pip3 install --user -e ." command, another error is given where it cannot find a version that satisfies the PySide2 requirement. I had no luck installing PySide2 as well. Using Qt isn't a must for me, I just want to get lag-free IP streaming on a simple GUI.

I'd really appreciate if you helped me out on this as it means a lot to me.

Thanks!

**Comment by elsampsa** [comment]
### libstdc++

The "libstdc++5" thing is an artifact.. libValkka does not depend on libstdc++5 at all, but for some reason I have it [here](https://github.com/elsampsa/valkka-core/blob/master/debian/control)

I need to remove the dependency to libstdc++N.  The problem is that I seem to be a complete amateur in these things (!) & have posted a stack overflow question here:

https://stackoverflow.com/questions/60043735/libstdc-as-a-dependency

If you know a guru that can answer that, please link him to that question.  :)

If I get no answer to that later this week, I'll just bite the bullet & remove that dependency.  Expect an updated version of libValkka in the ppa system later this week..

Meanwhile, if you'd like to try it out, you could compile libValkka on Jetson Nano from scratch as instructed [here](https://github.com/elsampsa/valkka-core#compile-yourself)

Before compiling, you could remote that dependency manually from the debian control file

### Qt

With the Qt problem, you are referring to [this](https://elsampsa.github.io/valkka-live/_build/html/requirements.html?highlight=hacky#hacky-mode)

First of all, libValkka does not depend on Qt, only Valkka Live does.

Wit libValkka you can use any GUI framework you want (GTK, Qt, etc.) as long as your GUI framework can access the X11 window ids

Compiling Qt with python bindings on Jetson Nano is a well-known feat.  I will post instructions on how to do that [here](https://elsampsa.github.io/valkka-examples/_build/html/index.html) later this week as well

**Comment by canozcivelek** [comment]
Thank you very much for the quick response and the explanations. I will try compiling myself and see if I can pull it off. In the mean time, please do let me know of any further updates on the matter as I will do the same.

Thank you again,

Best,

Can.

**Comment by elsampsa** [comment]
I'll update the packages in the ppa repo (and remove the libstdc++ dependency) once there is a bit more stuff to update to valkka core.  Meanwhile, I imagine that you have compiled libvalkka on jetson nano succesfully.  :)

Here are some tips to compile Qt on the darn thing:

https://elsampsa.github.io/valkka-examples/_build/html/knowledge.html#jetson-nano

**Comment by canozcivelek** [comment]
Hi, thank you for the updates! I wasn't able to compile it as I was working on other projects and waiting for an update from you. I will try it again once you update the packages. Also thanks for the tips on compiling Qt, I'll definitely check them out. 

Again, thank you for your efforts in helping me first hand and giving me updates, as not many are eager to do so. Really appreciate it!

**Comment by elsampsa** [comment]
in the latest version that you can get from the ppa repo, the stray dependencies have now been removed.  Please let us know if it helped.  :)

**Comment by canozcivelek** [comment]
Hi, sorry for the late reply, thank you for the update. I was able to make it work now. Thanks again, stay safe!
