### ISSUE TITLE
Disabling Syncing to vertical refresh enabled 

### ISSUE THREAD

**Issue by Ihebdhouibi** [elsampsa/valkka-core#25]
Hello everyone, 

I am currently developing a surveillance system using valkkalib, within openvalkka method I have a condition statement to check if vsync is activated or not.

Recently it start informing me that vsync is activated so I tried to disable it using 'export vblank_mode=0' at the terminal and it is already set to 0 

I checked with vblank_mode=0 glxgears and its printing +1000 frames per second which means it is disabled yet my program keeps informing me that vsync is activated and FireDetectorProcess is no longer detecting fire the way it used to since the vsync alert starts to kick in 

My question is the following, Should I add some lines of code into my python program to disable it ( eventhough checking from terminal tells it is actually disabled) ?

**Comment by elsampsa** [comment]
I guess you're relying heavily on the Qt example codes [here](https://github.com/elsampsa/valkka-examples/tree/master/api_level_2/qt) .. test_studio*.py, etc. right?

Which one of them exactly? ``test_studio_detector.py`` ?

You can disable that vsync warning by getting rid of this line the qt examples:
```
if (self.openglthread.hadVsync()):
```
What is FireDetectorProcess?  Your custom python multiprocess?

"FireDetectorProcess is no longer detecting fire the way it used to since the vsync alert starts to kick in"

Not sure why this is since I have no idea what's in your code.. in theory, any alert window popping up, should not block python multiprocess running in the background.

"no longer .. the way it used to".  What did it do? How did it used to do it? What is it not doing any longer?  Can't say..

"vsync alert starts to kick in".  A message on the terminal?  A Qt alert window?  What?

And one thing - the state of the qt examples is a bit messy.. Haven't had time to clean it up yet.  It also doesn't use the "state of the art"/latest multiprocessing framework.

If you want to use the latest multiprocessing framework coming with libValkka, please subclass from
``valkka.multiprocess.MessageProcess`` (the mother class is [here](https://github.com/elsampsa/valkka-core/blob/master/python/valkka/multiprocess/base.py)).  The latest multiprocessing framework is, btw, used by the [example project](https://github.com/elsampsa/valkka-examples/tree/master/example_projects/basic).

**Comment by Ihebdhouibi** [comment]
@elsampsa Yes I am using test_studio_detector.py

Getting rid of ` if (self.openglthread.hadVsync()):` may stop displaying the alert but Vsync is still activated right ? 

FireDetectorProcess is a python multiprocess that detects ongoing fire using color threshold, Before getting the Vsync is activated warning, the number of red pixels detected in each frame while there is ongoing fire was very high ( i,e +4000 red pixels ) Since I start getting that erreur the total number of red pixels dropped. My question is the following, do Vsync activated affect the quality of frames ? 

I will check out the example project, thank you

**Comment by Ihebdhouibi** [comment]
Solved : To make env variables permanent add this line to ~/.bashrc or ~/.profile
`export vblank_mode=0'`

Vsync will be disabled for ever.

That way it won't disappears after closing session.
